[project]
name = "llparse"
version = "0.1.3"
description = "A Parody of llparse written for writing C Parsers with Python"
readme = "README.md"
authors = [
    { name = "Vizonex", email = "VizonexBusiness@gmail.com" }
]
requires-python = ">=3.9"
dependencies = []

